
name: Bearer
on:
  pull_request:
  workflow_dispatch:
  push:
 
    branches:
      - main
jobs:
  NextGen-Static-Analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Bearer
      run: |
        curl -sfL https://raw.githubusercontent.com/Bearer/bearer/main/contrib/install.sh | sh 
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 8
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Bearer scan
      run: $bearer scan .
    
   
 
